/* @macrome
 * @generatedby @bablr/macrome-generator-bablr
 * @generatedfrom ./grammar.macro.js#c2557987c3d163ffd14b7c435b5dd3d507a974e8
 * This file is autogenerated. Please do not edit it directly.
 * When editing run `npx macrome watch` then change the file this is generated from.
 */
import _applyDecs from "@babel/runtime/helpers/applyDecs2305";
let _initProto, _ExpressionDecs, _ArrayDecs, _ObjectDecs, _StringDecs, _NumberDecs, _InfinityDecs, _BooleanDecs, _NullDecs, _KeywordDecs, _PunctuatorDecs, _ListDecs, _AnyDecs, _AllDecs;
import { re, spam as m } from '@bablr/boot';
import { basicTriviaEnhancer } from '@bablr/helpers/trivia';
import * as productions from '@bablr/helpers/productions';
import { o, eat, eatMatch, match, fail, defineAttribute } from '@bablr/helpers/grammar';
import { buildString } from '@bablr/helpers/builders';
import { Node, CoveredBy, AllowEmpty, InjectFrom, Literal } from '@bablr/helpers/decorators';
import * as Space from '@bablr/language-en-blank-space';
export const dependencies = {
  Space
};
export const canonicalURL = 'https://bablr.org/languages/core/en/json';
export const defaultMatcher = m`<_Expression />`;
const escapables = new Map(Object.entries({
  b: '\b',
  // these two escapes are antiquated
  f: '\f',
  // but giving their meaning away could be confusing
  n: '\n',
  r: '\r',
  t: '\t',
  0: '\0'
}));
export const grammar = basicTriviaEnhancer({
  triviaIsAllowed: s => s.span === 'Bare',
  triviaMatcher: m`#: :Space: <*Space /[ \n\r\t]/ />`
}, class JSONGrammar {
  static {
    [_initProto] = _applyDecs(this, [[_ExpressionDecs, 2, "Expression"], [_ArrayDecs, 2, "Array"], [_ObjectDecs, 2, "Object"], [Node, 2, "Property"], [_StringDecs, 2, "String"], [[AllowEmpty, Node], 2, "StringContent"], [Node, 2, "EscapeSequence"], [Node, 2, "EscapeCode"], [_NumberDecs, 2, "Number"], [Node, 2, "Integer"], [Node, 2, "UnsignedInteger"], [Node, 2, "UnsignedHexInteger"], [_InfinityDecs, 2, "Infinity"], [_BooleanDecs, 2, "Boolean"], [_NullDecs, 2, "Null"], [_KeywordDecs, 2, "Keyword"], [_PunctuatorDecs, 2, "Punctuator"], [_ListDecs, 2, "List"], [_AnyDecs, 2, "Any"], [_AllDecs, 2, "All"]], []).e;
  }
  constructor() {
    _initProto(this);
  }
  *[(_ExpressionDecs = CoveredBy('Element'), _ArrayDecs = [CoveredBy('Expression'), Node], _ObjectDecs = [CoveredBy('Expression'), Node], _StringDecs = [CoveredBy('Expression'), Node], _NumberDecs = [CoveredBy('Expression'), Node], _InfinityDecs = [CoveredBy('Expression'), Node], _BooleanDecs = [CoveredBy('Expression'), Node], _NullDecs = [CoveredBy('Expression'), Node], _KeywordDecs = [Literal, Node, InjectFrom(productions)], _PunctuatorDecs = [Literal, Node, InjectFrom(productions)], _ListDecs = [AllowEmpty, InjectFrom(productions)], _AnyDecs = InjectFrom(productions), _AllDecs = InjectFrom(productions), Symbol.for('@bablr/fragment'))]({
    props: {
      rootMatcher
    }
  }) {
    // needed for the trivia plugin
    yield eat(rootMatcher);
  }
  *Expression() {
    yield eat(m`<__Any />`, [m`<Array '[' />`, m`<Object '{' />`, m`<String /['"]/ />`, m`<Number /\d|-[\d\g]/ {span: 'Number'} />`, m`<Infinity /-?Infinity/ />`, m`<Null 'null' />`, m`<Boolean /true|false/ />`]);
  }
  *Array() {
    yield eat(m`openToken: <*Punctuator '[' { balanced: ']' } />`);
    yield eat(m`<__List />`, o({
      element: m`elements[]+$: <_Expression />`,
      separator: m`#separatorTokens[]: <*Punctuator ',' />`,
      allowTrailingSeparator: false
    }));
    yield eat(m`closeToken: <*Punctuator ']' { balancer: true } />`);
  }
  *Object() {
    yield eat(m`openToken: <*Punctuator '{' { balanced: '}' } />`);
    let sep = true;
    yield eatMatch(m`#separatorTokens[]: []`);
    yield eatMatch(m`properties[]$: []`);
    while (sep && (yield match(re`/.|\g/s`))) {
      let suppressGap = !!(yield match(m`<__All />`, [m`key: <//>`, m`sigilToken: <*Punctuator ':' />`]));
      yield eat(m`properties[]$: <Property />`, null, o({
        suppressGap
      }));
      sep = yield eatMatch(m`#separatorTokens[]: <*Punctuator ',' />`);
    }
    yield eat(m`closeToken: <*Punctuator '}' { balancer: true } />`);
  }
  *Property() {
    yield eat(m`key$: <String />`);
    yield eat(m`sigilToken: <*Punctuator ':' />`);
    yield eat(m`value+$: <_Expression />`);
  }
  *String() {
    yield eat(m`openToken: <*Punctuator '"' { balanced: '"', balancedSpan: 'String:Double' } />`);
    yield eat(m`content$: <*StringContent />`);
    yield eat(m`closeToken: <*Punctuator '"' { balancer: true } />`);
  }
  *StringContent({
    state: {
      span
    }
  }) {
    let esc, lit;
    do {
      esc = (yield match('\\')) && (yield eat(m`@: <EscapeSequence />`));
      lit = span === 'String:Single' ? yield eatMatch(re`/[^\r\n\\'\g]+/`) : yield eatMatch(re`/[^\r\n\\"\g]+/`);
    } while (esc || lit);
  }
  *EscapeSequence({
    state: {
      span
    },
    ctx
  }) {
    if (!span.startsWith('String')) {
      yield fail();
    }
    yield eat(m`sigilToken: <*Punctuator '\\' { openSpan: 'Escape' } />`);
    let match_;
    let cooked;
    if (match_ = span === 'String:Single' ? yield match(re`/[\\/bfnrt0']/`) : yield match(re`/[\\/bfnrt0"]/`)) {
      const matchText = ctx.sourceTextFor(match_);
      yield eat(m`code: <*Keyword ${buildString(matchText)} { closeSpan: 'Escape' } />`);
      cooked = escapables.get(matchText) || matchText;
    } else if (yield match('u')) {
      let codeNode = yield eat(m`code: <EscapeCode { closeSpan: 'Escape' } />`);
      const type = ctx.sourceTextFor(codeNode.get('typeToken'));
      if (type) {
        const value = ctx.sourceTextFor(codeNode.get('value'));
        if (!span.startsWith('String')) {
          throw new Error('not implemented');
        }
        if (type === 'u') {
          cooked = String.fromCharCode(parseInt(value, 16));
        } else {
          throw new Error();
        }
      } else {
        let value = ctx.sourceTextFor(codeNode);
        cooked = escapables.get(value) || value;
      }
    } else {
      yield fail();
    }
    yield defineAttribute('cooked', cooked);
  }
  *EscapeCode() {
    if (yield eatMatch(m`typeToken: <*Keyword 'u' />`)) {
      if (yield eatMatch(m`openToken: <*Punctuator '{' { balanced: '}' } />`, null, o({
        bind: true
      }))) {
        yield eat(m`value$: <*UnsignedHexInteger />`);
        yield eat(m`closeToken: <*Punctuator '}' { balancer: true } />`);
      } else {
        yield eat(m`value$: <*UnsignedHexInteger /[\da-fA-F]{4}/ />`);
        yield eat(m`closeToken: null`);
      }
    }
  }
  *Number() {
    yield eat(m`wholePart$: <Integer />`, o({
      noDoubleZero: true,
      matchSign: '-'
    }));
    let fs = yield eatMatch(m`fractionalSeparatorToken: <*Punctuator '.' />`, null, o({
      bind: true
    }));
    if (fs) {
      yield eat(m`fractionalPart$: <*UnsignedInteger />`);
    } else {
      yield eat(m`fractionalPart$: null`);
    }
    let es = yield eatMatch(m`exponentSeparatorToken: <*Punctuator /[eE]/ />`, null, o({
      bind: true
    }));
    if (es) {
      yield eat(m`exponentPart$: <Integer />`, {
        matchSign: /[+-]/
      });
    } else {
      yield eat(m`exponentPart$: null`);
    }
  }
  *Integer({
    props: {
      matchSign = null,
      noDoubleZero = false
    }
  }) {
    if (matchSign) {
      yield eatMatch(m`signToken: <*Punctuator ${buildString(matchSign)} />`, null, o({
        bind: true
      }));
    } else {
      yield eat(m`signToken: null`);
    }
    yield eat(m`value$: <*UnsignedInteger />`, o({
      noDoubleZero
    }));
  }
  *UnsignedInteger({
    props: {
      noDoubleZero = false
    },
    ctx
  }) {
    let firstDigit = ctx.sourceTextFor(yield eat(re`/\d/`));
    if (!noDoubleZero || firstDigit.value !== '0') {
      yield eatMatch(re`/\d+/`);
    }
  }
  *UnsignedHexInteger() {
    yield eatMatch(re`/[\da-fA-F]+/`);
  }
  *Infinity() {
    yield eatMatch(m`signToken: <*Punctuator '-' />`, null, o({
      bind: true
    }));
    yield eat(m`sigilToken: <*Keyword 'Infinity' />`);
  }
  *Boolean() {
    yield eat(m`sigilToken: <*Keyword /true|false/ />`);
  }
  *Null() {
    yield eat(m`sigilToken: <*Keyword 'null' />`);
  }
  *Keyword() {}
  *Punctuator() {}
  *List() {}
  *Any() {}
  *All() {}
});